CineExplorer/Controllers/TripController.cs
using CineExplorer.Models;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace CineExplorer.Controllers
{
    public class TripController : Controller
    {

        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static TripController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44344/api/");
        }

        // GET: Trips
        public ActionResult Index()
        {
            string url = "TripsData/ListTrips";
            HttpResponseMessage response = client.GetAsync(url).Result;

            IEnumerable<Trip> trips = response.Content.ReadAsAsync<IEnumerable<Trip>>().Result;
            return View(trips);
        }

        // GET: Trips/Show/5
        public ActionResult Show(int id)
        {
            string url = "TripData/FindTrip/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;

            Trip trip = response.Content.ReadAsAsync<Trip>().Result;

            return View(trip);
        }

        // GET: Trips/Create
        [Authorize]
        public ActionResult New()
        {
            string url = "LocationData/ListLocations";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<Location> Locations = response.Content.ReadAsAsync<IEnumerable<Location>>().Result;
            return View(Locations);
        }

        // POST: Trips/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create(Trip trip, int? movieId, List<int> selectedLocations)
        {
            if (selectedLocations == null || !selectedLocations.Any())
            {
                ModelState.AddModelError("", "At least one location must be selected.");

                // Repopulate locations for the view
                if (movieId.HasValue)
                {
                    string movieUrl = $"MovieData/FindMovie/{movieId}";
                    HttpResponseMessage movieResponse = client.GetAsync(movieUrl).Result;
                    Movie movie = movieResponse.Content.ReadAsAsync<Movie>().Result;

                    ViewBag.MovieName = movie.Name;
                    ViewBag.MovieLocations = movie.Locations;
                }
                else
                {
                    string url = "LocationData/ListLocations";
                    HttpResponseMessage locationsResponse = client.GetAsync(url).Result;
                    ViewBag.AllLocations = locationsResponse.Content.ReadAsAsync<IEnumerable<Location>>().Result;
                }

                return View("New", trip);
            }

            trip.UserId = User.Identity.GetUserId();
            trip.Location = new List<Location>();

            foreach (var locationId in selectedLocations)
            {
                string url = $"LocationData/FindLocation/{locationId}";
                HttpResponseMessage locationresponse = client.GetAsync(url).Result;
                Location locationData = locationresponse.Content.ReadAsAsync<Location>().Result;
                trip.Location.Add(locationData);
            }

            string createUrl = "TripData/AddTrip";
            string jsonpayload = jss.Serialize(trip);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";

            HttpResponseMessage response = client.PostAsync(createUrl, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                // Repopulate locations for the view in case of error
                if (movieId.HasValue)
                {
                    string movieUrl = $"MovieData/FindMovie/{movieId}";
                    HttpResponseMessage movieResponse = client.GetAsync(movieUrl).Result;
                    Movie movie = movieResponse.Content.ReadAsAsync<Movie>().Result;

                    ViewBag.MovieName = movie.Name;
                    ViewBag.MovieLocations = movie.Locations;
                }
                else
                {
                    string url = "LocationData/ListLocations";
                    HttpResponseMessage locationsResponse = client.GetAsync(url).Result;
                    ViewBag.AllLocations = locationsResponse.Content.ReadAsAsync<IEnumerable<Location>>().Result;
                }

                return View("New", trip);
            }
        }

        // GET: Trips/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            string url = $"TripsData/FindTrip/{id}";
            HttpResponseMessage response = client.GetAsync(url).Result;

            Trip trip = response.Content.ReadAsAsync<Trip>().Result;
            return View(trip);
        }

        // POST: Trips/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult Edit(int id, Trip trip)
        {
            string url = $"TripsData/UpdateTrip/{id}";

            string jsonpayload = jss.Serialize(trip);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";

            HttpResponseMessage response = client.PostAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(trip);
            }
        }

        // GET: Trips/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            string url = $"TripsData/FindTrip/{id}";
            HttpResponseMessage response = client.GetAsync(url).Result;

            Trip trip = response.Content.ReadAsAsync<Trip>().Result;
            return View(trip);
        }

        // POST: Trips/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize]
        public ActionResult DeleteConfirmed(int id)
        {
            string url = $"TripsData/DeleteTrip/{id}";
            HttpResponseMessage response = client.PostAsync(url, null).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return new HttpStatusCodeResult(System.Net.HttpStatusCode.InternalServerError);
            }
        }



    }
}

CineExplorer/Views/Trip/New.cshtml
@model CineExplorer.Models.Trip

<h2>Create New Trip</h2>

@using (Html.BeginForm("Create", "Trip", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.TripName)
        @Html.EditorFor(model => model.TripName, new { htmlAttributes = new { @class = "form-control", required = "required" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.TripDescription)
        @Html.TextAreaFor(model => model.TripDescription, new { @class = "form-control", required = "required" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate)
        @Html.EditorFor(model => model.StartDate, new { htmlAttributes = new { @class = "form-control", type = "date", required = "required" } })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate)
        @Html.EditorFor(model => model.EndDate, new { htmlAttributes = new { @class = "form-control", type = "date", required = "required" } })
    </div>

    if (ViewBag.MovieId != null)
    {
        <input type="hidden" name="movieId" value="@ViewBag.MovieId" />
        <p>Select locations from the movie: @ViewBag.MovieName (at least one is required)</p>
        <div class="form-group">
            @foreach (var location in ViewBag.MovieLocations)
            {
                <div class="form-check">
                    <input type="checkbox" name="selectedLocations" value="@location.LocationId" class="form-check-input location-checkbox" id="location-@location.LocationId" />
                    <label class="form-check-label" for="location-@location.LocationId">@location.Name, @location.City, @location.Country</label>
                </div>
            }
        </div>
    }
    else
    {
        <div class="form-group">
            <label>Select Locations (at least one is required)</label>
            @foreach (var location in ViewBag.AllLocations)
            {
                <div class="form-check">
                    <input type="checkbox" name="selectedLocations" value="@location.LocationId" class="form-check-input location-checkbox" id="location-@location.LocationId" />
                    <label class="form-check-label" for="location-@location.LocationId">@location.Name, @location.City, @location.Country</label>
                </div>
            }
        </div>
    }

    <button type="submit" class="btn btn-primary" id="submitButton">Create Trip</button>
}

@section Scripts {
    <script>$(document).ready(function () {
            $('#submitButton').click(function (e) {
                if ($('.location-checkbox:checked').length === 0) {
                    e.preventDefault();
                    alert('Please select at least one location for your trip.');
                }
            });
        });</script>
}

CineExplorer/Views/Trip/Show.cshtml
@model CineExplorer.Models.Trip

@{
    ViewData["Title"] = "Trip Details";
}

<h1>Trip Details</h1>

<div>
    <h4>Trip</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Trip Name
        </dt>
        <dd class="col-sm-10">
            @Model.TripName
        </dd>
        <dt class="col-sm-2">
            Description
        </dt>
        <dd class="col-sm-10">
            @Model.TripDescription
        </dd>
        <dt class="col-sm-2">
            Start Date
        </dt>
        <dd class="col-sm-10">
            @Model.StartDate.ToString("yyyy-MM-dd")
        </dd>
        <dt class="col-sm-2">
            End Date
        </dt>
        <dd class="col-sm-10">
            @Model.EndDate.ToString("yyyy-MM-dd")
        </dd>
        <dt class="col-sm-2">
            Customer
        </dt>
        <dd class="col-sm-10">
            @Model.User.UserName
        </dd>
        <dt class="col-sm-2">
            Places
        </dt>
        <dd class="col-sm-10">
            <ul>
                @foreach (var location in Model.Location)
                {
                    <li>@location.Name (@location.City)</li>
                    <a href="/Review/Create/@location.LocationId" class="btn btn-sm btn-primary">Add Review</a>
                }
            </ul>
        </dd>
    </dl>
</div>

<div>
    <a href="/Trip/Edit/@Model.TripId" class="btn btn-sm btn-secondary">Edit</a>
    <a href="/Trip/List" class="btn btn-secondary">Back to List</a>
</div>