CineExplorer/Models/Location.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CineExplorer.Models
{
    public class Location
    {
        [Key]
        public int LocationId { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string ImageURL { get; set; }

        [Display(Name = "Upload Image")]
        public HttpPostedFileBase ImageFile { get; set; }

        //A location can belong to multiple trips
        public ICollection<Trip> Trips { get; set; }

        //A location can belong to multiple Movies
        public ICollection<Movie> Movies { get; set; }

        public Location()
        {
            Movies = new HashSet<Movie>();
        }



    }

}

CineExplorer/Controllers/LocationController.cs
using CineExplorer.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace CineExplorer.Controllers
{
    public class LocationController : Controller
    {
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static LocationController()
        {
            client = new HttpClient();
            client.BaseAddress = new Uri("https://localhost:44344/api/LocationData/");
        }

        // GET: Location
        public ActionResult Index()
        {
            string url = "ListLocations";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<Location> locations = response.Content.ReadAsAsync<IEnumerable<Location>>().Result;
            return View(locations);
        }

        // GET: Location/Details/5
        public async Task<ActionResult> Details(int id)
        {
            HttpResponseMessage locationResponse = await client.GetAsync($"LocationData/FindLocation/{id}");
            if (locationResponse.IsSuccessStatusCode)
            {
                var location = await locationResponse.Content.ReadAsAsync<Location>();

                // Fetch reviews for this location
                HttpResponseMessage reviewsResponse = await client.GetAsync($"ReviewData/GetReviewsForLocation/{id}");
                if (reviewsResponse.IsSuccessStatusCode)
                {
                    var reviews = await reviewsResponse.Content.ReadAsAsync<List<Review>>();
                    ViewBag.Reviews = reviews;
                }

                return View(location);
            }
            return HttpNotFound();
        }

        // GET: Location/Create
        [Authorize(Users = "admin@testmail.com")]
        public ActionResult Create()
        {
            string url = "MovieData/ListMovies";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<Movie> Movies = response.Content.ReadAsAsync<IEnumerable<Movie>>().Result;
            return View(Movies);
        }

        // POST: Location/Create
        [HttpPost]
        [Authorize(Users = "admin@testmail.com")]
        public ActionResult Create(Location location, HttpPostedFileBase ImageFile, int[] selectedMovies)
        {
            string url = "AddLocation";

            if (ImageFile != null && ImageFile.ContentLength > 0)
            {
                var fileName = Path.GetFileName(ImageFile.FileName);
                var path = Path.Combine(Server.MapPath("~/Uploads"), fileName);
                ImageFile.SaveAs(path);
                location.ImageURL = "/Uploads/" + fileName;
            }

            var locationWithMovies = new
            {
                Location = location,
                MovieIds = selectedMovies
            };

            HttpResponseMessage response = client.PostAsJsonAsync(url, locationWithMovies).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }

            // If we got this far, something failed, redisplay form
            url = "MovieData/ListMovies";
            HttpResponseMessage movieResponse = client.GetAsync(url).Result;
            if (movieResponse.IsSuccessStatusCode)
            {
                var movies = movieResponse.Content.ReadAsAsync<IEnumerable<Movie>>().Result;
                ViewBag.Movies = movies;
            }
            return View(location);
        }

        // GET: Location/Edit/5
        [Authorize(Users = "admin@testmail.com")]
        public ActionResult Edit(int id)
        {
            string url = $"FindLocation/{id}";
            HttpResponseMessage response = client.GetAsync(url).Result;
            Location location = response.Content.ReadAsAsync<Location>().Result;
            return View(location);
        }

        // POST: Location/Edit/5
        [HttpPost]
        [Authorize(Users = "admin@testmail.com")]
        public ActionResult Edit(int id, Location location)
        {
            string url = $"UpdateLocation/{id}";
            string jsonpayload = jss.Serialize(location);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PutAsync(url, content).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(location);
            }
        }

        // GET: Location/Delete/5
        [Authorize(Users = "admin@testmail.com")]
        public ActionResult Delete(int id)
        {
            string url = $"FindLocation/{id}";
            HttpResponseMessage response = client.GetAsync(url).Result;
            Location location = response.Content.ReadAsAsync<Location>().Result;
            return View(location);
        }

        // POST: Location/Delete/5
        [HttpPost]
        [Authorize(Users = "admin@testmail.com")]
        public ActionResult Delete(int id, Location location)
        {
            string url = $"DeleteLocation/{id}";
            HttpResponseMessage response = client.DeleteAsync(url).Result;
            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("Index");
            }
            else
            {
                return View(location);
            }
        }
    }
}

CineExplorer/Views/Location/Create.cshtml
@model CineExplorer.Models.Location

@{
    ViewBag.Title = "Create Location";
}

<h2>Create Location</h2>

<div class="container">
    <h4>Location Details</h4>
    <hr />

    @using (Html.BeginForm("Create", "Location", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()

        <div class="row">
            <div class="col-md-8">
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label" })
                    @Html.EditorFor(model => model.Country, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
                </div>
                <div class="form-group">
                    @Html.Label("Image", htmlAttributes: new { @class = "control-label" })
                    <input type="file" name="ImageFile" class="form-control" />
                </div>
                <div class="form-group">
                    @Html.Label("Associated Movies", htmlAttributes: new { @class = "control-label" })
                    <select name="selectedMovies" multiple class="form-control">
                        @foreach (var movie in ViewBag.Movies)
                        {
                            <option value="@movie.MovieId">@movie.Title</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <input type="submit" value="Create" class="btn btn-primary" />
                </div>
            </div>
        </div>
    }
</div>

<div class="mt-3">
    <a href="/Location/Index" class="btn btn-secondary">Back to List</a>
</div>

CineExplorer/Views/Location/Delete.cshtml
@model CineExplorer.Models.Location

@{
    ViewBag.Title = "Delete Location";
}

<h2>Delete Location</h2>

<h3>Are you sure you want to delete this?</h3>

<div class="row">
    <div class="col-md-6">
        <h4>Location Details</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-4">Name</dt>
            <dd class="col-sm-8">@Model.Name</dd>

            <dt class="col-sm-4">City</dt>
            <dd class="col-sm-8">@Model.City</dd>

            <dt class="col-sm-4">Country</dt>
            <dd class="col-sm-8">@Model.Country</dd>
        </dl>

        @if (!string.IsNullOrEmpty(Model.ImageURL))
        {
            <div class="mb-3">
                <img src="@Model.ImageURL" alt="Location Image" class="img-fluid" style="max-width: 200px;" />
            </div>
        }

        <form action="@Url.Action("Delete", "Location", new { id = Model.LocationId })" method="POST">
            @Html.AntiForgeryToken()
            <input type="submit" value="Delete" class="btn btn-danger" />
        </form>
    </div>
</div>

<div class="mt-3">
    <a href="@Url.Action("Index", "Location")" class="btn btn-secondary">Back to List</a>
</div>

CineExplorer/Views/Location/Details.cshtml
@model CineExplorer.Models.Location

@{
    ViewBag.Title = "Location Details";
}

<h2>Location Details</h2>

<div>
    <h4>Location</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-3">Name</dt>
        <dd class="col-sm-9">@Model.Name</dd>

        <dt class="col-sm-3">City</dt>
        <dd class="col-sm-9">@Model.City</dd>

        <dt class="col-sm-3">Country</dt>
        <dd class="col-sm-9">@Model.Country</dd>
    </dl>

    @if (!string.IsNullOrEmpty(Model.ImageURL))
    {
        <div class="mb-3">
            <img src="@Model.ImageURL" alt="Location Image" class="img-fluid" style="max-width: 300px; margin-top: 10px;" />
        </div>
    }

    <h4>Associated Movies</h4>
    @if (Model.Movies != null && Model.Movies.Any())
    {
        <ul class="list-group">
            @foreach (var movie in Model.Movies)
            {
                <li class="list-group-item">@movie.Name</li>
            }
        </ul>
    }
    else
    {
        <p>No movies associated with this location.</p>
    }

    <h4>Reviews</h4>
    @if (ViewBag.Reviews != null && ViewBag.Reviews.Count > 0)
    {
        <ul class="list-group">
            @foreach (var review in ViewBag.Reviews)
            {
                <li class="list-group-item">
                    <strong>@review.Title</strong> - Rating: @review.Rating
                    <p>@review.Content</p>
                </li>
            }
        </ul>
    }
    else
    {
        <p>No reviews available for this location.</p>
    }
</div>

<p>
    <a href="@Url.Action("Edit", "Location", new { id = Model.LocationId })" class="btn btn-primary">Edit</a>
    <a href="@Url.Action("Index", "Location")" class="btn btn-secondary">Back to List</a>
</p>

CineExplorer/Views/Location/Edit.cshtml
@model CineExplorer.Models.Location

@{
    ViewBag.Title = "Edit Location";
}

<h2>Edit Location</h2>

<div class="row">
    <div class="col-md-8">
        @using (Html.BeginForm("Edit", "Location", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.City, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Country, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(model => model.Country, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Country, "", new { @class = "text-danger" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ImageFile, htmlAttributes: new { @class = "control-label" })
                <input type="file" name="ImageFile" class="form-control" />
                @if (!string.IsNullOrEmpty(Model.ImageURL))
                {
                    <div class="mt-3">
                        <img src="@Model.ImageURL" alt="Current Image" class="img-fluid" style="max-width: 200px;" />
                    </div>
                }
            </div>

            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        }
    </div>
</div>

<div class="mt-3">
    <a href="@Url.Action("Index", "Location")" class="btn btn-secondary">Back to List</a>
</div>

CineExplorer/Views/Location/Index.cshtml
@model IEnumerable<CineExplorer.Models.Location>

@{
    ViewBag.Title = "Locations";
}

<h2 class="mb-4">Locations</h2>

@if (User.Identity.Name == "admin@testmail.com")
{
    <p>
        @Html.ActionLink("Create New", "Create", null, new { @class = "btn btn-primary" })
    </p>
}

<table class="table table-striped table-hover">
    <thead class="thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.First().Name)</th>
            <th>@Html.DisplayNameFor(model => model.First().City)</th>
            <th>@Html.DisplayNameFor(model => model.First().Country)</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.City)</td>
                <td>@Html.DisplayFor(modelItem => item.Country)</td>
                <td>
                    @Html.ActionLink("Details", "Details", new { id = item.LocationId }, new { @class = "btn btn-info btn-sm" })
                    @if (User.Identity.Name == "admin@testmail.com")
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.LocationId }, new { @class = "btn btn-warning btn-sm" })
                        @Html.ActionLink("Delete", "Delete", new { id = item.LocationId }, new { @class = "btn btn-danger btn-sm" })
                    }
                </td>
            </tr>
        }
    </tbody>
</table>